// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/categories': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories').default>>>>
    }
    '/api/admin/categories/upload': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories/upload').default>>>>
    }
    '/api/admin/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/login').default>>>>
    }
    '/api/admin/products': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products').default>>>>
    }
    '/api/admin/upload': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/upload').default>>>>
    }
    '/api/categories': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories').default>>>>
    }
    '/api/products': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.4.8_019ec01b8e16a9d8ee1af529f78c6768/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}